# Site settings
title: royaso的jekyll博客
email: zhangroyaso@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  开始尝试使用jekyll来写博客，
  技术类学习
baseurl: "/test" # the subpath of your site, e.g. /blog/
url: "http://blog.royaso.com" # the base hostname & protocol for your site
twitter_username: royaso
github_username:  royaso

# Build settings
markdown: kramdown
